# Generated by Django 3.0.8 on 2020-07-09 06:15

from django.db import migrations
import django.utils.timezone
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushroomspot',
            name='geom',
            field=djgeojson.fields.PolygonField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
