# Generated by Django 3.0.8 on 2020-07-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mushroomspot_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='MciArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=30)),
                ('lng', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SmsStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.IntegerField()),
                ('message', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(choices=[(0, 'در صف ارسال'), (1, 'ارسال شده'), (2, 'مشکل در ارسال')])),
            ],
        ),
    ]
