# Generated by Django 3.0.8 on 2020-07-19 03:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='co',
            new_name='value',
        ),
        migrations.AddField(
            model_name='alert',
            name='key',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
