# Generated by Django 3.0.8 on 2020-07-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200719_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='receptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('area', models.IntegerField()),
            ],
        ),
    ]
