# Generated by Django 3.0.8 on 2020-10-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_road', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cell_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.IntegerField(default=0),
        ),
    ]
