# Generated by Django 3.0.8 on 2020-10-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_road', '0002_auto_20201014_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.IntegerField(null=True),
        ),
    ]
